export default [{
        animeEmoji: '👑👦🍜👍👦🍜🍜👍🏻👍🏻🏻👦👦🍜👍🏻',
        animeName: 'Yojouhan Shinwa Taikei',
        animeYear: 2010,
        animeLink: 'https://myanimelist.net/anime/7785/Yojouhan_Shinwa_Taikei',
    },
    {
        animeEmoji: '👑👦🍜👍👦👦🍜👍🏻🍜👍🏻👍🏻🏻👦👦🍜👍🏻',
        animeName: 'Ore Monogatari!!',
        animeYear: 2015,
        animeLink: 'https://myanimelist.net/anime/28297/Ore_Monogatari',
    },
    {
        animeEmoji: '️👑👦🍜👍🏻👑👦👦🍜👍🏻🍜👍🏻👍🏻🏻👦👦🍜👍🏻',
        animeName: 'Ookami Kodomo no Ame to Yuki',
        animeYear: 2012,
        animeLink: 'https://myanimelist.net/anime/12355/Ookami_Kodomo_no_Ame_to_Yuki',
    },
    {
        animeEmoji: '👑👦🍜👍🏻👍🏻👑👦👦🍜👍🏻🍜👍🏻👍🏻🏻👦👦🍜👍🏻',
        animeName: 'Toki wo Kakeru Shoujo',
        animeYear: 2006,
        animeLink: 'https://myanimelist.net/anime/2236/Toki_wo_Kakeru_Shoujo',
    },
    {
        animeEmoji: ' ️👑👍🏻👑👦🍜👍🏻👍🏻🏻👦',
        animeName: 'Noragami',
        animeYear: 2014,
        animeLink: 'https://myanimelist.net/anime/20507/Noragami',
    },
    {
        animeEmoji: ' ️👑👍👦🍜🏻👑👦🍜👍🏻👍🏻🏻👦',
        animeName: 'High School DxD',
        animeYear: 2012,
        animeLink: 'https://myanimelist.net/anime/11617/High_School_DxD',
    },
    {
        animeEmoji: '🎆💪🌧',
        animeName: 'Weathering with You',
        animeYear: 2019,
        animeLink: 'https://myanimelist.net/anime/38826/Tenki_no_Ko',
    },
    {
        animeEmoji: '🎆🍜🏻💪🌧',
        animeName: 'Fullmetal Alchemist: Brotherhood',
        animeYear: 2009,
        animeLink: 'https://myanimelist.net/anime/5114/Fullmetal_Alchemist__Brotherhood',
    },
    {
        animeEmoji: '🎆🍜🏻💪🌧👍🏻🏻',
        animeName: 'Shingeki no Kyojin Season 3 Part 2',
        animeYear: 2019,
        animeLink: 'https://myanimelist.net/anime/38524/Shingeki_no_Kyojin_Season_3_Part_2',
    },
    {
        animeEmoji: '🧒👨🍜💪',
        animeName: 'Naruto: Shippuuden',
        animeYear: 2007,
        animeLink: 'https://myanimelist.net/anime/1735/Naruto__Shippuuden',
    },
    {
        animeEmoji: '🧒💪🍔',
        animeName: 'Boruto: Naruto The Next Generation',
        animeYear: 2017,
        animeLink: 'https://myanimelist.net/anime/34566/Boruto__Naruto_Next_Generations',
    },
    {
        animeEmoji: '❤️😺👍👧',
        animeName: 'Nakitai Watashi wa Neko o Kaburu',
        animeYear: 2020,
        animeLink: 'https://myanimelist.net/anime/41168/Nakitai_Watashi_wa_Neko_wo_Kaburu',
    },
    {
        animeEmoji: '🎆🔮👍🏻🏻',
        animeName: 'Another World',
        animeYear: 2019,
        animeLink: 'https://myanimelist.net/anime/40295/Another_World',
    },
    {
        animeEmoji: '🎆🏻🪄',
        animeName: 'Hello World',
        animeYear: 2019,
        animeLink: 'https://myanimelist.net/anime/38816/Hello_World',
    },
    {
        animeEmoji: '🎆🍜👍🏻👍🏻🏻👦🏻🪄',
        animeName: 'SteinsGate',
        animeYear: 2011,
        animeLink: 'https://myanimelist.net/anime/9253/Steins_Gate',
    },
    {
        animeEmoji: '🍜👍🏻👍🏻🏻👦🏻🪄',
        animeName: 'Gintama',
        animeYear: 2015,
        animeLink: 'https://myanimelist.net/anime/28977/Gintama',
    },
    {
        animeEmoji: '👧👍🌃☁️',
        animeName: 'Sora no Aosa wo Shiru Hito yo',
        animeYear: 2020,
        animeLink: 'https://myanimelist.net/anime/39569/Sora_no_Aosa_wo_Shiru_Hito_yo',
    },
    {
        animeEmoji: '🏡💖😘👩🏻👨🏻',
        animeName: 'Kotonoha no Niwa',
        animeYear: 2013,
        animeLink: 'https://myanimelist.net/anime/16782/Kotonoha_no_Niwa',
    },
    {
        animeEmoji: '👧🏻👦🏻⛅👍🏻',
        animeName: 'Mirai no Mirai',
        animeYear: 2019,
        animeLink: 'https://myanimelist.net/anime/36936/Mirai_no_Mirai',
    },
    {
        animeEmoji: '🤖👦🏻👍🏻💖',
        animeName: 'Stand by Me Doraemon 2',
        animeYear: 2020,
        animeLink: 'https://myanimelist.net/anime/40853/Stand_By_Me_Doraemon_2',
    },
    {
        animeEmoji: '🤖🍜👍🏻👦🏻👍🏻💖',
        animeName: 'Fruits Basket: The Final',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/42938/Fruits_Basket__The_Final',
    },
    {
        animeEmoji: '🤖👍🏻👦🏻👍🏻💖',
        animeName: 'Ginga Eiyuu Densetsu',
        animeYear: 1982,
        animeLink: 'https://myanimelist.net/anime/820/Ginga_Eiyuu_Densetsu',
    },
    {
        animeEmoji: '👍🏻🏻👦👦🤖👍🏻👦🏻👍👍🏻🏻👦👦🏻💖',
        animeName: 'Koe no Katachi',
        animeYear: 2016,
        animeLink: 'https://myanimelist.net/anime/28851/Koe_no_Katachi',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍👍🏻🏻👦👦🏻💖',
        animeName: 'Clannad: After Story',
        animeYear: 2008,
        animeLink: 'https://myanimelist.net/anime/4181/Clannad__After_Story',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍👍🏻👦👦🏻💖',
        animeName: 'Code Geass: Hangyaku no Lelouch R2',
        animeYear: 2008,
        animeLink: 'https://myanimelist.net/anime/2904/Code_Geass__Hangyaku_no_Lelouch_R2',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍🏻👦👦🏻💖',
        animeName: 'Kimi no Na wa',
        animeYear: 2016,
        animeLink: 'https://myanimelist.net/anime/32281/Kimi_no_Na_wa',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍🏻👦👦🏻',
        animeName: 'Shiguang Dailiren',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/44074/Shiguang_Dailiren',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍🏻👦🏻',
        animeName: 'Violet Evergarden Movie',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/37987/Violet_Evergarden_Movie',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍🏻👦🏻🏡💖',
        animeName: 'Bakemonogatari',
        animeYear: 2009,
        animeLink: 'https://myanimelist.net/anime/5081/Bakemonogatari',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍🏻👦🏻🏡💖👍🏻👦',
        animeName: 'Toradora!',
        animeYear: 2008,
        animeLink: 'https://myanimelist.net/anime/4224/Toradora',
    },
    {
        animeEmoji: '👍🏻🏻👦👦👍🏻👦🏻👍🏻👦🏻🌃☁️👍🏻👦',
        animeName: 'Planetes',
        animeYear: 2003,
        animeLink: 'https://myanimelist.net/anime/329/Planetes',
    },
    {
        animeEmoji: '🍜👍🏻🍜👍🏻👍🏻🏻👍🏻🏻👦👍🏻👦🏻🌃☁️👍🏻👦',
        animeName: 'Katanagatari',
        animeYear: 2010,
        animeLink: 'https://myanimelist.net/anime/6594/Katanagatari',
    },
    {
        animeEmoji: '👍🏻🏻👦🌃☁️🍜👍🏻🍜👍🏻👍🏻🏻🌃☁️👍🏻👦',
        animeName: 'Digimon Savers',
        animeYear: 2006,
        animeLink: 'https://myanimelist.net/anime/859/Digimon_Savers',
    },
    {
        animeEmoji: '👍🏻🏻👦🌃🏻👦🌃☁️🌃☁️👍🏻👦',
        animeName: 'Yu☆Gi☆Oh! Zexal Second',
        animeYear: 2012,
        animeLink: 'https://myanimelist.net/anime/15489/Yu%E2%98%86Gi%E2%98%86Oh_Zexal_Second',
    },
    {
        animeEmoji: '👍🏻🏻👦🌃🍜👍🏻🍜👍🏻👍🏻🏻☁️🌃☁️👍🏻👦',
        animeName: 'Metal Fight Beyblade: Baku',
        animeYear: 2010,
        animeLink: 'https://myanimelist.net/anime/8410/Metal_Fight_Beyblade__Baku',
    } {
        animeEmoji: '👍🏻🏻🍜👍🏻🍜👍🏻👍🏻🏻👦🌃☁️🌃☁️👍🏻👦',
        animeName: 'Yahari Ore no Seishun Love Comedy wa Machigatteiru.',
        animeYear: 2013,
        animeLink: 'https://myanimelist.net/anime/14813/Yahari_Ore_no_Seishun_Love_Comedy_wa_Machigatteiru',
    },
    {
        animeEmoji: '👍🏻🏻👦🌃☁️🌃☁️👦🍜👍🏻🍜👍🏻👍🏻🏻',
        animeName: 'Shakunetsu Kabaddi',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/42395/Shakunetsu_Kabaddi',
    },
    {
        animeEmoji: '👍🏻🏻👦🌃☁️🌃☁️👦🍜👍🏻🍜👍🏻🏻🏻',
        animeName: 'Hoshiai no Sora',
        animeYear: 2019,
        animeLink: 'https://myanimelist.net/anime/37972/Hoshiai_no_Sora',
    },
    {
        animeEmoji: '👍🏻🏻🌃☁️🌃☁️👦🍜👍🏻🍜👍🏻🏻🏻',
        animeName: 'Nichijou',
        animeYear: 2011,
        animeLink: 'https://myanimelist.net/anime/10165/Nichijou',
    },
    {
        animeEmoji: '👍🏻🏻🌃☁️🌃☁️👦👍🏻🍜👍🏻🏻🏻',
        animeName: 'Tokyo Revengers',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/42249/Tokyo_Revengers',
    },
    {
        animeEmoji: '👑👦👍🏻🏻🌃☁️🌃👑👦☁️👦👍🏻👑👦🍜👍🏻🏻🏻👑👦',
        animeName: 'Mushoku Tensei: Isekai Ittara Honki Dasu 2nd Season',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/45576/Mushoku_Tensei__Isekai_Ittara_Honki_Dasu_2nd_Season',
    },
    {
        animeEmoji: '👑👦👍🏻🏻🌃☁️🌃👑☁️👦👍🏻👑👦🍜👍🏻🏻🏻👑👦',
        animeName: 'Mo Dao Zu Shi: Wanjie Pian',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/40434/Mo_Dao_Zu_Shi__Wanjie_Pian',
    },
    {
        animeEmoji: '👑👦👍🏻🏻🌃☁️🌃👑☁️👦👍🏻👑👦🍜👍🏻🏻👑👦',
        animeName: '86 2nd Season',
        animeYear: 2021,
        animeLink: 'https://myanimelist.net/anime/48569/86_2nd_Season',
    },
    {
        animeEmoji: '👑👦👍🏻🏻🌃☁️🌃☁️👦👍🏻👑👦🍜👍🏻🏻👑👦',
        animeName: 'One Piece',
        animeYear: 1999,
        animeLink: 'https://myanimelist.net/anime/21/One_Piece',
    },
    {
        animeEmoji: '👑👦👍🏻🏻☁️🌃☁️👦👍🏻👑👦🍜👍🏻🏻👑👦',
        animeName: 'Kingdom 3rd Season',
        animeYear: 2020,
        animeLink: 'https://myanimelist.net/anime/40682/Kingdom_3rd_Season',
    },
    {
        animeEmoji: '👑👦👍🏻🏻☁️🌃☁️👦👍🏻👑👦🍜👍🏻👑👦',
        animeName: 'Holo no Graffiti',
        animeYear: 2019,
        animeLink: 'https://myanimelist.net/anime/44042/Holo_no_Graffiti',
    },
    {
        animeEmoji: '👑👦👍🏻🏻☁️🌃☁️👦👑👦🍜👍🏻👑👦',
        animeName: 'Detective Conan',
        animeYear: 1996,
        animeLink: 'https://myanimelist.net/anime/235/Detective_Conan',
    },
    {
        animeEmoji: '👑👦👍🏻🏻🌃☁️👦👑👦🍜👍🏻👑👦',
        animeName: 'Fate/Grand Carnival',
        animeYear: 2020,
        animeLink: 'https://myanimelist.net/anime/44248/Fate_Grand_Carnival',
    },
    {
        animeEmoji: '👑️👑👦👍🏻🏻🌃☁️👦👑👦🍜👍🏻👑👦',
        animeName: 'Haikyuu!!',
        animeYear: 2014,
        animeLink: 'https://myanimelist.net/anime/20583/Haikyuu',
    },
    {
        animeEmoji: '👑👦👍🏻🏻️👑🌃☁️👦👑👦🍜👍🏻👑👦',
        animeName: 'Haikyuu!! Second Season',
        animeYear: 2015,
        animeLink: 'https://myanimelist.net/anime/28891/Haikyuu_Second_Season',
    },
    {
        animeEmoji: '👑👦👍🏻🏻🌃️👑☁️👦👑👦🍜👍🏻👑👦',
        animeName: 'Kuroko no Basket',
        animeYear: 2012,
        animeLink: 'https://myanimelist.net/anime/11771/Kuroko_no_Basket',
    },
    {
        animeEmoji: '👑👦👍🏻🏻🌃☁️👦👑👦🍜👍🏻️👑👑👦',
        animeName: 'Yuri!!! on Ice',
        animeYear: 2016,
        animeLink: 'https://myanimelist.net/anime/32995/Yuri_',
    },
    {
        animeEmoji: '👑👦👍🏻🌃☁️👦👑👦🍜👍🏻️👑👑👦',
        animeName: 'Shingeki no Kyojin',
        animeYear: 2013,
        animeLink: 'https://myanimelist.net/anime/16498/Shingeki_no_Kyojin',
    },
    {
        animeEmoji: '👑👦👍🏻🌃☁️👦👦🍜👍🏻️👑👑👦',
        animeName: 'Psycho-Pass',
        animeYear: 2012,
        animeLink: 'https://myanimelist.net/anime/13601/Psycho-Pass',
    },
    {
        animeEmoji: '👑👦👍🏻🌃☁️👦🍜👍🏻️👑👑👦',
        animeName: 'Guilty Crown',
        animeYear: 2011,
        animeLink: 'https://myanimelist.net/anime/10793/Guilty_Crown',
    },
    {
        animeEmoji: '👑👦👍🏻🌃☁️👦🍜👍🏻️👑👑👦',
        animeName: 'Steins Gate',
        animeYear: 2011,
        animeLink: 'https://myanimelist.net/anime/9253/Steins_Gate',
    },
];